title: "Japanese to Legalese"
author: "Macaulay Curtis"
description: "A blog about translating legal language and other linguistic curiosities." # This will show up in places like twitter, linkedin, etc, if you share your sites url as a post.
email: contact@asociis.co.jp
future: false # GitHub Pages will publish future posts if this isn't set to false
timezone: Japan/Tokyo

# Email / Social media user names used by the minima theme:
# All of these are optional and can be removed or commented out
email: "contact@asociis.co.jp"
linkedin_username: "macaulay-curtis"

#########################################################################################
######### Nothing below needs to be changed (unless you know what you're doing) #########
#########################################################################################
remote_theme: pages-themes/minimal@v0.2.0

rss: rss

kramdown:
  syntax_highlighter_opts:
    disable: true
    
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tags

header_pages:
  - archive.md
  - materials.md

titles_from_headings:
  strip_title: true
  collections:
    materials:
        output: true
    digressions:
        output: true

defaults:
  - scope:
      path: ""
      type: post
    values:
      tags: Other
